---
Name: silverstripe-image-recipe
---
Kinglozzer\SilverstripePicture\Img:
  extensions:
    - Bigfork\SilverstripeImageRecipe\ObjectPositionExtension
    - Bigfork\SilverstripeImageRecipe\WebpEnablerExtension
Kinglozzer\SilverstripePicture\Source:
  extensions:
    - Bigfork\SilverstripeImageRecipe\WebpEnablerExtension
