---
Name: silverstripe-image-recipe
---
Kinglozzer\SilverstripePicture\Img:
  extensions:
    - Bigfork\SilverstripeImageRecipe\ObjectPositionExtension
    - Bigfork\SilverstripeImageRecipe\WebpEnablerExtension
    - Bigfork\SilverstripeImageRecipe\ImgAltTextExtension
Kinglozzer\SilverstripePicture\Source:
  extensions:
    - Bigfork\SilverstripeImageRecipe\WebpEnablerExtension
SilverStripe\Assets\Storage\DBFile:
  extensions:
    - Bigfork\SilverstripeImageRecipe\ImageAltTextExtension
SilverStripe\Assets\Image:
  extensions:
    - Bigfork\SilverstripeImageRecipe\ImageAltTextExtension
